### ISSUE TITLE
Change the Style/AccessorGrouping cop to :separated

### ISSUE THREAD

**Issue by Bodacious** [boxt/boxt_ruby_style_guide#27]
This is a personal preference of mine, but I wanted to raise it with the rest of the team in case there's a significant number of people who agree.

Basically, this cop: https://docs.rubocop.org/rubocop/cops_style.html#styleaccessorgrouping

Will convert this:

``` ruby
class Monkey
  attr_reader :name 
  attr_reader :bananas 
  attr_reader :classification
end
```

Into this:

``` ruby
class Monkey
  attr_reader :name, :bananas, :classification
end
```

---

I prefer the first style for three main reasons: 

1. It allows better documentation for each attribute, which should generally be encouraged:
    ``` ruby
    class Monkey
      ##
      # String with this monkey's given name
      attr_reader :name 

      ##
      # Array of Bananas belonging to this monkey (see Banana class).
      attr_reader :bananas 

      ##
      # Classification of monkey (see Classification class).
      attr_reader :classification
    end
    ```
2. It's easier to read. I find if there are more than six or seven attributes in a list, it becomes a mess and difficult to read.
3. Long lists of attributes, when automatically fixed using `rubocop -a`, will often become longer than the maximum line length cop, which means they have to be broken up across multiple lines in any case.

As always, I'm happy to be outvoted on this issue, but wanted to raise the suggestion in case it was a common preference in the team.

**Comment by MattHall** [comment]
Yep - I prefer separated too. Neater.
